name: Monthly Data Pipeline

on:
  schedule:
    # Run on the 1st of every month at 00:00 UTC
    - cron: '0 0 1 * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  update_data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Fetch data from WorldBank API
        run: |
          python src/fetch_worldbank_data.py
          
      - name: Clean and transform data
        run: |
          python src/data_cleaning.py
          
      - name: Generate EDA and visualizations
        run: |
          python analysis/generate_eda.py
          
      - name: Generate additional visualizations
        run: |
          python analysis/generate_visualizations.py
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/*.csv data/*.json analysis/plots/*.png
          git commit -m "Monthly data update: $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push