name: 'global_connectivity'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"
  - "logs"

models:
  global_connectivity:
    staging:
      +materialized: view
      +schema: staging
    analytics:
      +materialized: table
      +schema: analytics